language: php

php:
- '7.0'
- '5.6'

before_install:
  - nvm install node
  - nvm alias default node
  - node --version
  - composer install
  - npm install
  - npm run wp-install
  - npm run wp-start >/dev/null 2>&1 &

script:
  - npm test
