language: php

php:
- '7.0'
- '5.6'

before_install:
  - composer install
  - mysql -e "create database IF NOT EXISTS wordpress;" -uroot
  - bash bin/install-wp.sh
  - npm install
  - npm start

script:
  - npm test
